### ISSUE TITLE
Monitoring:Connection Error

### ISSUE THREAD

**Issue by ZenTauren** [PurityWasHere/DeadSplatter#13]
Mine keeps spamming this, the ram usage never changes. Any idea what I could be doing wrong?

2020-08-28 23:24:15.284868|Monitoring:Connection Error | PID:0 | Current Ram Usage:79.1% | Ram Cutoff:90%

**Comment by PureIsntHere** [comment]
I pushed an update that should fix fallback mode not updating Ram usage. Although the reason it's working that way is due to the script not getting the permissions it needs to check the server's memory usage. A workaround that works for some is to run through elevated PowerShell

**Comment by ZenTauren** [comment]
The update you pushed solved the connection error, but the current ram usage seems to update 2 or 3 times, then it gets stuck on the same value that keeps repeating.

**Comment by PureIsntHere** [comment]
It looks like your script is losing access to the server while running then. That's a new issue I haven't seen yet. I'll try to work out a fix soon.

**Comment by PureIsntHere** [comment]
I just pushed a new update. The script should be able to now properly track system usage in fallback mode. The error was caused by an issue with variables not being set correctly.

**Comment by PureIsntHere** [comment]
Also for your permission issues, I would recommend running the script through elevated Powershell if you haven't already. That fixes permission issues for many of the users on windows server builds.

**Comment by ZenTauren** [comment]
My PowerShell is always running as admin. The system ram usage is working now, or it was always working and I couldn't see it. The current ram usage is still stuck though. The current ram usage is always 25.16%. At least I can use the script now, by setting it up for system ram.

**Comment by PureIsntHere** [comment]
Yea i updated it in an attempt at fixing your issue. I can’t find anyway to force the script to have permissions if your windows server build doesn’t want it to.

**Comment by ZenTauren** [comment]
The pre-compiled version works correctly for me, so I'm closing this.

You should add a configurable timer that restarts the server.
